import { ORDER_STATUSES } from "../status"

const statusList = {}

const statusNext = (currentStatus) => {
    statusList[ORDER_STATUSES.FRESH] = ORDER_STATUSES.PREPARING
    statusList[ORDER_STATUSES.PREPARING] = ORDER_STATUSES.READY_FOR_PICKUP
    statusList[ORDER_STATUSES.READY_FOR_PICKUP] = ORDER_STATUSES.DISPATCHED
    statusList[ORDER_STATUSES.DISPATCHED] = ORDER_STATUSES.DELIVERED
    statusList[ORDER_STATUSES.DELIVERED] = ORDER_STATUSES.INVOICED
    statusList[ORDER_STATUSES.INVOICED] = ORDER_STATUSES.PENDING_PAYMENT
    statusList[ORDER_STATUSES.PENDING_PAYMENT] = ORDER_STATUSES.INVOICED
    return statusList[currentStatus]
}

export { statusNext }